version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      all:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      dev-deps:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
      prod-deps:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"