version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

    # Ignore all major-version bumps
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

    # Group remaining (minor + patch) into one PR
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

    # Ignore all major-version bumps
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

    # Two buckets: prod vs dev deps
    groups:
      prod-deps:
        dependency-type: "production"
        patterns:
          - "*"
      dev-deps:
        dependency-type: "development"
        patterns:
          - "*"
