version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

    # Only consider minor and patch updates
    allow:
      - update-type: "version-update:semver-minor"
      - update-type: "version-update:semver-patch"

    # Group all allowed updates into one PR
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"

    # Only consider minor and patch updates for both prod & dev deps
    allow:
      - dependency-type: "production"
        update-type: "version-update:semver-minor"
      - dependency-type: "production"
        update-type: "version-update:semver-patch"
      - dependency-type: "development"
        update-type: "version-update:semver-minor"
      - dependency-type: "development"
        update-type: "version-update:semver-patch"

    # Merge prod and dev updates into separate PRs
    groups:
      prod-deps:
        dependency-type: "production"
        patterns:
          - "*"
      dev-deps:
        dependency-type: "development"
        patterns:
          - "*"
