kind: pipeline
name: build
platform:
  arch: amd64
trigger:
  branch:
  - master
  event:
  - push
steps:
- name: publish-image
  image: plugins/docker
  settings:
    repo: ghcr.io/pheelee/cat
    username:
      from_secret: ghcr_user
    password:
      from_secret: ghcr_token
    registry: ghcr.io
    tags: latest
- name: deploy
  image: plugins/webhook
  settings:
    urls: https://deploy.irbe.ch/v1/update
    method: GET
    token-value:
      from_secret: DEPLOY_API_TOKEN
---
kind: pipeline
name: artifacts
steps:
- name: build
  image: golang
  environment:
    CGO_ENABLED: 0
  commands:
  - GOOS=linux GOARCH=amd64 go build -o dist/Cat-linux-amd64 ./cmd/Cat/
  - GOOS=linux GOARCH=386 go build -o dist/Cat-linux-386 ./cmd/Cat/
  - GOOS=linux GOARCH=arm64 go build -o dist/Cat-linux-arm64 ./cmd/Cat/
  - GOOS=linux GOARCH=arm GOARM=7 go build -o dist/Cat-linux-armv7 ./cmd/Cat/
  - GOOS=windows GOARCH=amd64 go build -o dist/Cat-win-amd64.exe ./cmd/Cat/
  - GOOS=windows GOARCH=386 go build -o dist/Cat-win-386.exe ./cmd/Cat/
  
- name: publish-artifacts
  image: plugins/gitea-release
  settings:
    api_key: 
      from_secret: gitea_api_key
    base_url: https://git.dockernet.ch
    files: dist/*
trigger:
  event:
  - tag