kind: pipeline
name: build
platform:
  arch: amd64
steps:
- name: publish-image
  image: plugins/docker
  settings:
    repo: registry.dockernet.ch/pheelee/cat
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: registry.dockernet.ch
    tags: latest
- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: p2.irbe.ch
    username: deploy
    password: 
      from_secret: ssh_password
    port: 22
    script:
      - cat.irbe.ch prod
trigger:
  branch:
  - master
  event:
  - push
---
kind: pipeline
name: artifacts
steps:
- name: build
  image: golang
  environment:
    CGO_ENABLED: 0
  commands:
  - GOOS=linux GOARCH=amd64 go build -o dist/Cat-linux-amd64 ./cmd/Cat/
  - GOOS=linux GOARCH=386 go build -o dist/Cat-linux-386 ./cmd/Cat/
  - GOOS=linux GOARCH=arm64 go build -o dist/Cat-linux-arm64 ./cmd/Cat/
  - GOOS=linux GOARCH=arm GOARM=7 go build -o dist/Cat-linux-armv7 ./cmd/Cat/
  - GOOS=windows GOARCH=amd64 go build -o dist/Cat-win-amd64.exe ./cmd/Cat/
  - GOOS=windows GOARCH=386 go build -o dist/Cat-win-386.exe ./cmd/Cat/
  
- name: publish-artifacts
  image: pheelee/drone-gitea-release
  settings:
    api_key: 
      from_secret: gitea_api_key
    base_url: https://git.dockernet.ch
    files: dist/*
trigger:
  event:
  - tag